version: 2
jobs:
  build-gateway:
    working_directory: ~/deploy-gke-example/apigateway
    docker:
      - image: circleci/openjdk:8u252-jdk
    steps:
      - checkout:
          path: ~/deploy-gke-example
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Build
          command: ./gradlew clean build

workflows:
  version: 2
  my-workflow:
    jobs:
      - build-gateway
      # - build-bill
      # - build-report
      # - build-product
      # - deploy-web
