version: 2
jobs:
  build-gateway:
    working_directory: ~/test-soa/apigateway
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/test-soa
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run :
          name: Auth to gcloud
          command: |
            echo $GCLOUD_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${PROJECT_ID}
            gcloud auth configure-docker
      - run :
          name: Build and push docker images
          command: |
            # docker build -t asia.gcr.io/soa-group-7-174/api-gateway:$CIRCLE_BUILD_NUM .
            # docker push asia.gcr.io/soa-group-7-174/api-gateway:$CIRCLE_BUILD_NUM

  build-bill:
    working_directory: ~/test-soa/bill
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/test-soa
      - setup_remote_docker:
          docker_layer_caching: true
      # - run:
      #     name: chmod permissions
      #     command: chmod +x ./gradlew
      - run :
          name: Auth to gcloud
          command: |
            echo $GCLOUD_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${PROJECT_ID}
            gcloud container clusters get-credentials soa-service --zone asia-southeast1-b --project soa-group-7-174
            gcloud auth configure-docker
      - run :
          name: Build and push docker images
          command: |
            # docker build -t asia.gcr.io/soa-group-7-174/bill:$CIRCLE_BUILD_NUM .
            # docker push asia.gcr.io/soa-group-7-174/bill:$CIRCLE_BUILD_NUM

  build-product:
    working_directory: ~/test-soa/product
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/test-soa
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: chmod permissions
          command: chmod +x ./mvnw
      - run :
          name: Auth to gcloud
          command: |
            echo $GCLOUD_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${PROJECT_ID}
            gcloud container clusters get-credentials soa-service --zone asia-southeast1-b --project soa-group-7-174
            gcloud auth configure-docker
      - run :
          name: Build and push docker images
          command: |
            docker build -t asia.gcr.io/soa-group-7-174/product:$CIRCLE_BUILD_NUM .
            docker push asia.gcr.io/soa-group-7-174/product:$CIRCLE_BUILD_NUM
            kubectl set image deployment/product product=asia.gcr.io/soa-group-7-174/product:$CIRCLE_BUILD_NUM

  build-web:
    working_directory: ~/test-soa/web
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/test-soa
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: build web
          command: |
            npm install
            yarn build
      - save_cache:
          key: yarn-build-{{ .Revision }}
          paths: 
            - ~/.build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - store_test_results:
          path: build
  
  deploy-web:
    docker:
      - image: google/cloud-sdk

      - image: circleci/node:10
      
    working_directory: ~/test-soa/web
    steps:
      - checkout:
          path: ~/test-soa
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: yarn-build-{{ .Revision }}
      - run:
          name: Build web
          command: |
            npm install
            yarn build
      - run :
          name: Auth to gcloud
          command: |
            echo $GCLOUD_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${PROJECT_ID}
            gcloud container clusters get-credentials soa-service --zone asia-southeast1-b --project soa-group-7-174
            gcloud auth configure-docker
      - run :
          name: Build image and push docker images
          command: |
            docker build -t asia.gcr.io/soa-group-7-174/web:$CIRCLE_BUILD_NUM .
            docker push asia.gcr.io/soa-group-7-174/web:$CIRCLE_BUILD_NUM
            # kubectl set image deployment/web web=asia.gcr.io/soa-group-7-174/web:$CIRCLE_BUILD_NUM


workflows:
  version: 2
  workflow:
    jobs:
      # - build-gateway
      # - build-bill
      # - build-product
      # - build-web
      - deploy-web
          # requires:
          #   - build-web